name: Run NGX ETL Script Daily

on:
  schedule:
    # Weekdays at 4:30pm WAT (WAT = UTC+1) -> 15:30 UTC
    - cron: '30 15 * * 1-5'
  workflow_dispatch: # manual run button in Actions

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          which chromedriver
          chromedriver --version
          
      - name: Detect ChromeDriver
        run: |
          echo "CHROME_DRIVER_PATH=$(which chromedriver)"
          chromedriver --version

      - name: Verify ChromeDriver
        run: |
          ls -l $(which chromedriver)
          chromedriver --version
      
      - name: Run ETL script
        env:
          NEON_CONN: ${{ secrets.NEON_CONN }}
          NEON_TABLE: ${{ secrets.NEON_TABLE }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          if python ngx_etl.py; then
            echo "ETL script completed successfully ✅"
            echo "success" > etl_status.txt
          else
            echo "ETL script failed ❌"
            echo "failed" > etl_status.txt
            exit 1
          fi

      - name: Display Final Status
        if: always()
        run: |
          echo "===================="
          echo "FINAL STATUS:"
          cat etl_status.txt || echo "No status file found."
          echo "===================="
