name: Run NGX ETL Script Daily

on:
  schedule:
    # Weekdays at 4:30pm WAT (WAT = UTC+1) -> 15:30 UTC
    - cron: '30 15 * * 1-5'
  workflow_dispatch: # manual run button in Actions

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          which chromedriver
          chromedriver --version

      - name: Run ETL script
        env:
          NEON_CONN: ${{ secrets.NEON_CONN }}
          NEON_TABLE: ${{ secrets.NEON_TABLE }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python ngx_etl.py

      - name: Send GitHub notification
        run: |
          gh api repos/${{ github.repository }}/dispatches \
            -f event_type='etl_run_complete' \
            -f client_payload='{"message":"NGX ETL run completed successfully."}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
